

server:
  port: 8080



spring:
  application:
    name: "Planner"
  config:
    import:  "optional:configserver:http://localhost:8081/"
  profiles:
    active: "prod"
  datasource:
    url:  jdbc:mysql://localhost:3560/floridaplanner
    username: root
    password: rootpassword
  jpa:
   show-sql: true
  sql:
    init:
      mode: always


logging:
  level:
    root: DEBUG

application1:
  update: "I am adding the spring cloud config  "



#
#    datasource:
#      url: jdbc:mysql://localhost:3307/accountsdbv4
#      username: root
#      password: root
#    jpa:
#      show-sql: true
#    sql:
#      init:
#        mode: always
#    config:
#      import: "optional:configserver:http://localhost:8071/"










